import type { CollectionConfig } from 'payload'

import { ownStudentData, staffOnly } from '@/access/coaching'

export const IndependentPractices: CollectionConfig = {
  slug: 'independent-practices',
  labels: { singular: 'Student Home Practice', plural: 'Student Home Practice Progress' },
  access: {
    create: staffOnly,
    delete: staffOnly,
    read: ownStudentData,
    update: staffOnly,
  },
  admin: {
    group: 'Training',
    useAsTitle: 'title',
    defaultColumns: [
      'title',
      'student',
      'program',
      'lessonWeek',
      'timerStatus',
      'currentDrillIndex',
      'elapsedSeconds',
      'status',
    ],
  },
  fields: [
    {
      name: 'practiceKey',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: { hidden: true },
    },
    { name: 'title', type: 'text', required: true },
    {
      name: 'practice',
      type: 'relationship',
      relationTo: 'practice-library',
      required: true,
      maxDepth: 2,
    },
    {
      name: 'student',
      type: 'relationship',
      relationTo: 'student-profiles',
      required: true,
      index: true,
      maxDepth: 2,
    },
    { name: 'program', type: 'relationship', relationTo: 'programs', required: true, maxDepth: 1 },
    { name: 'phase', type: 'text', required: true },
    { name: 'lessonWeek', type: 'number', required: true, min: 1, index: true },
    { name: 'instructions', type: 'textarea', required: true },
    {
      name: 'drills',
      type: 'relationship',
      relationTo: 'drills',
      hasMany: true,
      required: true,
      minRows: 1,
      maxDepth: 1,
    },
    { name: 'successCriteria', type: 'textarea', required: true },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'assigned',
      options: ['assigned', 'completed'],
    },
    {
      name: 'timerStatus',
      type: 'select',
      required: true,
      defaultValue: 'not-started',
      options: [
        { label: 'Not started', value: 'not-started' },
        { label: 'Running', value: 'running' },
        { label: 'Paused', value: 'paused' },
        { label: 'Finished', value: 'finished' },
      ],
      admin: {
        readOnly: true,
        description: 'Current state of the student’s home-practice timer.',
      },
    },
    {
      name: 'timerStartedAt',
      type: 'date',
      admin: {
        readOnly: true,
        date: { pickerAppearance: 'dayAndTime' },
        description: 'Start time for the currently running timer segment.',
      },
    },
    {
      name: 'elapsedSeconds',
      type: 'number',
      required: true,
      min: 0,
      defaultValue: 0,
      admin: {
        readOnly: true,
        description: 'Accumulated practice time in seconds.',
      },
    },
    {
      name: 'currentDrillIndex',
      type: 'number',
      required: true,
      min: 0,
      defaultValue: 0,
      admin: {
        readOnly: true,
        description: 'Zero-based position of the active drill in the guided practice modal.',
      },
    },
    {
      name: 'currentDrillElapsedSeconds',
      type: 'number',
      required: true,
      min: 0,
      defaultValue: 0,
      admin: {
        readOnly: true,
        description: 'Accumulated time for the active drill countdown.',
      },
    },
    {
      name: 'currentStepIndex',
      type: 'number',
      required: true,
      min: 0,
      defaultValue: 0,
      admin: {
        readOnly: true,
        description: 'Zero-based position of the active exercise inside the current drill.',
      },
    },
    {
      name: 'currentRound',
      type: 'number',
      required: true,
      min: 1,
      defaultValue: 1,
      admin: {
        readOnly: true,
        description: 'One-based round number inside the active home-practice drill.',
      },
    },
    {
      name: 'currentStepElapsedSeconds',
      type: 'number',
      required: true,
      min: 0,
      defaultValue: 0,
      admin: {
        readOnly: true,
        description: 'Accumulated time for the active exercise.',
      },
    },
    {
      name: 'exerciseLogs',
      type: 'array',
      labels: { singular: 'Exercise log', plural: 'Exercise logs' },
      defaultValue: [],
      admin: {
        readOnly: true,
        description: 'Elapsed time recorded whenever a student completes an exercise.',
      },
      fields: [
        { name: 'drillIndex', type: 'number', required: true, min: 0 },
        { name: 'round', type: 'number', required: true, min: 1 },
        { name: 'stepIndex', type: 'number', required: true, min: 0 },
        { name: 'elapsedSeconds', type: 'number', required: true, min: 0 },
        { name: 'completedAt', type: 'date', required: true },
      ],
    },
    { name: 'completedAt', type: 'date', admin: { date: { pickerAppearance: 'dayAndTime' } } },
    { name: 'coachFeedback', type: 'textarea' },
  ],
}
