/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    programs: Program;
    skills: Skill;
    drills: Drill;
    'practice-library': PracticeLibrary;
    'student-profiles': StudentProfile;
    'training-sessions': TrainingSession;
    'skill-progress': SkillProgress;
    'session-skill-scores': SessionSkillScore;
    assignments: Assignment;
    'independent-practices': IndependentPractice;
    'coaching-events': CoachingEvent;
    'coach-availability': CoachAvailability;
    'coach-availability-rules': CoachAvailabilityRule;
    'assessment-bookings': AssessmentBooking;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    programs: {
      independentPractices: 'independent-practices';
    };
    'student-profiles': {
      trainingSessions: 'training-sessions';
      skillDevelopment: 'skill-progress';
      independentPracticeProgress: 'independent-practices';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    drills: DrillsSelect<false> | DrillsSelect<true>;
    'practice-library': PracticeLibrarySelect<false> | PracticeLibrarySelect<true>;
    'student-profiles': StudentProfilesSelect<false> | StudentProfilesSelect<true>;
    'training-sessions': TrainingSessionsSelect<false> | TrainingSessionsSelect<true>;
    'skill-progress': SkillProgressSelect<false> | SkillProgressSelect<true>;
    'session-skill-scores': SessionSkillScoresSelect<false> | SessionSkillScoresSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    'independent-practices': IndependentPracticesSelect<false> | IndependentPracticesSelect<true>;
    'coaching-events': CoachingEventsSelect<false> | CoachingEventsSelect<true>;
    'coach-availability': CoachAvailabilitySelect<false> | CoachAvailabilitySelect<true>;
    'coach-availability-rules': CoachAvailabilityRulesSelect<false> | CoachAvailabilityRulesSelect<true>;
    'assessment-bookings': AssessmentBookingsSelect<false> | AssessmentBookingsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'coaching-settings': CoachingSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'coaching-settings': CoachingSettingsSelect<false> | CoachingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendAssessmentReminder: TaskSendAssessmentReminder;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CoachHeroBlock
    | DevelopmentLoopBlock
    | ProgramsGridBlock
    | AssessmentStepsBlock
    | TrainingCycleBlock
    | ProgressProfileBlock
    | CoachingQuoteBlock
    | CoachingCTABlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  googleSubject?: string | null;
  roles: ('admin' | 'coach' | 'student')[];
  accountStatus?: ('pending' | 'active') | null;
  invitationAcceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachHeroBlock".
 */
export interface CoachHeroBlock {
  eyebrow: string;
  heading: string;
  highlight: string;
  description: string;
  primaryButton: {
    label: string;
    url: string;
  };
  secondaryButton: {
    label: string;
    url: string;
  };
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  dashboard: {
    label: string;
    title: string;
    status: string;
    stage: string;
    skill: string;
    feedback: string;
    progress: number;
    drillLabel: string;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'coachHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DevelopmentLoopBlock".
 */
export interface DevelopmentLoopBlock {
  label: string;
  steps?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'developmentLoop';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock".
 */
export interface ProgramsGridBlock {
  anchor?: string | null;
  eyebrow: string;
  heading: string;
  description: string;
  programs?:
    | {
        number: string;
        audience: string;
        name: string;
        description: string;
        skills?:
          | {
              skill: string;
              id?: string | null;
            }[]
          | null;
        linkLabel: string;
        linkURL: string;
        accent: 'sky' | 'blue' | 'navy';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'programsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssessmentStepsBlock".
 */
export interface AssessmentStepsBlock {
  anchor?: string | null;
  eyebrow: string;
  heading: string;
  description: string;
  stepLabel: string;
  button: {
    label: string;
    url: string;
  };
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'assessmentSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrainingCycleBlock".
 */
export interface TrainingCycleBlock {
  eyebrow: string;
  heading: string;
  note?: string | null;
  sessions?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trainingCycle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgressProfileBlock".
 */
export interface ProgressProfileBlock {
  eyebrow: string;
  heading: string;
  description: string;
  stages?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  profileTitle: string;
  profileLabel: string;
  skills?:
    | {
        name: string;
        stage: string;
        progress: number;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'progressProfile';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachingQuoteBlock".
 */
export interface CoachingQuoteBlock {
  quote: string;
  attribution: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coachingQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachingCTABlock".
 */
export interface CoachingCTABlock {
  anchor?: string | null;
  eyebrow: string;
  heading: string;
  button: {
    label: string;
    url: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'coachingCTA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: string;
  name: string;
  level: 'foundations' | 'development' | 'competitive';
  description: string;
  durationWeeks: number;
  phases: {
    name: string;
    description?: string | null;
    order: number;
    startWeek: number;
    endWeek: number;
    lessons: {
      week: number;
      title: string;
      lessonType: 'technical' | 'movement' | 'tactical' | 'match-play' | 'assessment';
      objective: string;
      /**
       * Program sessions start at 60 minutes. Coaches can adjust an individual session to 90 or 120 minutes.
       */
      durationMinutes: number;
      /**
       * Automatically derived from the lesson drills. Generated sessions and coach scorecards use this exact list.
       */
      skills: (string | Skill)[];
      drills: (string | Drill)[];
      /**
       * Optional event-specific court and home drills. The player’s preferred event selects the matching branch.
       */
      eventVariants?: {
        singlesDrills?: (string | Drill)[] | null;
        doublesDrills?: (string | Drill)[] | null;
        singlesHomeDrills?: (string | Drill)[] | null;
        doublesHomeDrills?: (string | Drill)[] | null;
      };
      /**
       * Weekly guidance shown to the student above the generated home-practice drills.
       */
      homePracticeInstructions: string;
      /**
       * Exercises assigned for this lesson. Saving the program automatically builds and updates the student home-practice plan.
       */
      homeDrills: (string | Drill)[];
      /**
       * Automatically generated from the selected Home Drills.
       */
      independentPractice: string | PracticeLibrary;
      successCriteria: string;
      sessionPlan: {
        warmUp: string;
        movementPreparation: string;
        conditionedGame: string;
        matchPlay: string;
        cooldownAndFeedback: string;
      };
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  independentPractices?: {
    docs?: (string | IndependentPractice)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  name: string;
  category:
    | 'stroke-technique'
    | 'footwork'
    | 'consistency'
    | 'tactical-decisions'
    | 'match-performance'
    | 'physical-readiness'
    | 'training-habits';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drills".
 */
export interface Drill {
  id: string;
  name: string;
  skill: string | Skill;
  level: 'foundations' | 'development' | 'competitive';
  eventType: 'general' | 'singles' | 'doubles';
  /**
   * Controls whether this drill is available in the home-practice library.
   */
  practiceSetting: 'home' | 'court';
  equipment: string;
  numberOfPlayers: number;
  durationMinutes: number;
  instructions: string;
  coachingPoints: string;
  commonMistakes?: string | null;
  difficulty: 'easy' | 'moderate' | 'challenging';
  /**
   * Optional tutorial shown before this drill. Replace the external reference with your own secure video URL when it is ready.
   */
  videoURL?: string | null;
  /**
   * Public image path used for drill cards and detail views.
   */
  illustrationURL?: string | null;
  /**
   * Contact sheet used to illustrate each numbered home-practice exercise.
   */
  stepIllustrationURL?: string | null;
  stepIllustrationColumns?: number | null;
  stepIllustrationRows?: number | null;
  /**
   * Numbered exercises shown as individual illustrated cards in guided home practice.
   */
  practiceSteps?:
    | {
        title: string;
        instruction: string;
        amount: string;
        durationSeconds?: number | null;
        id?: string | null;
      }[]
    | null;
  successTarget: string;
  easierVariation?: string | null;
  harderProgression?: string | null;
  completionRequirement?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-library".
 */
export interface PracticeLibrary {
  id: string;
  name: string;
  level: 'foundations' | 'development' | 'competitive';
  instructions: string;
  drills: (string | Drill)[];
  durationMinutes: number;
  successCriteria: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "independent-practices".
 */
export interface IndependentPractice {
  id: string;
  practiceKey: string;
  title: string;
  practice: string | PracticeLibrary;
  student: string | StudentProfile;
  program: string | Program;
  phase: string;
  lessonWeek: number;
  instructions: string;
  drills: (string | Drill)[];
  successCriteria: string;
  status: 'assigned' | 'completed';
  /**
   * Current state of the student’s home-practice timer.
   */
  timerStatus: 'not-started' | 'running' | 'paused' | 'finished';
  /**
   * Start time for the currently running timer segment.
   */
  timerStartedAt?: string | null;
  /**
   * Accumulated practice time in seconds.
   */
  elapsedSeconds: number;
  /**
   * Zero-based position of the active drill in the guided practice modal.
   */
  currentDrillIndex: number;
  /**
   * Accumulated time for the active drill countdown.
   */
  currentDrillElapsedSeconds: number;
  /**
   * Zero-based position of the active exercise inside the current drill.
   */
  currentStepIndex: number;
  /**
   * One-based round number inside the active home-practice drill.
   */
  currentRound: number;
  /**
   * Accumulated time for the active exercise.
   */
  currentStepElapsedSeconds: number;
  /**
   * Elapsed time recorded whenever a student completes an exercise.
   */
  exerciseLogs?:
    | {
        drillIndex: number;
        round: number;
        stepIndex: number;
        elapsedSeconds: number;
        completedAt: string;
        id?: string | null;
      }[]
    | null;
  completedAt?: string | null;
  coachFeedback?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-profiles".
 */
export interface StudentProfile {
  id: string;
  displayName: string;
  user: string | User;
  coach?: (string | null) | User;
  program?: (string | null) | Program;
  /**
   * Automatically points to the first program lesson that has not been completed.
   */
  currentProgramWeek: number;
  /**
   * Automatically derived from the current program lesson.
   */
  currentPhase: string;
  /**
   * Automatically derived from the current program lesson.
   */
  weeklyFocus: string;
  /**
   * Automatically derived from the current program lesson objective.
   */
  focusExplanation: string;
  /**
   * Automatically uses the assigned program name.
   */
  packageName: string;
  /**
   * Automatically uses the number of lessons in the assigned program.
   */
  packageSessions: number;
  /**
   * Automatically recalculated from completed program sessions.
   */
  sessionsRemaining: number;
  attendanceRate: number;
  assessmentStatus: 'required' | 'scheduled' | 'current';
  lastTrainingAt?: string | null;
  /**
   * Captured during student onboarding.
   */
  playingExperience?: ('new' | 'under-1-year' | '1-3-years' | 'over-3-years') | null;
  /**
   * Captured during student onboarding.
   */
  preferredEvent?: ('singles' | 'doubles' | 'both' | 'not-sure') | null;
  /**
   * Applies to every planned and scheduled lesson in this player’s current program.
   */
  trainingDurationMinutes?: number | null;
  /**
   * What the student wants to achieve. Captured during onboarding.
   */
  goals?: string | null;
  /**
   * When the student is available to train. Captured during onboarding.
   */
  trainingAvailability?: string | null;
  /**
   * Any injuries or health notes. Captured during onboarding.
   */
  injuryConsiderations?: string | null;
  /**
   * When the student accepted the health-data use notice.
   */
  healthDataConsentAt?: string | null;
  /**
   * Policy version accepted with the health-data consent.
   */
  privacyPolicyVersion?: string | null;
  /**
   * Student self-rating from 1 (beginner) to 10 (advanced). Captured during onboarding.
   */
  skillSelfRating?: number | null;
  /**
   * How often the student can train. Captured during onboarding.
   */
  trainingFrequencyPerWeek?: ('1' | '2' | '3' | '4+') | null;
  /**
   * The student’s competitive ambition. Captured during onboarding.
   */
  competitionGoal?: ('casual' | 'club' | 'tournament' | 'national') | null;
  /**
   * Automatically derived from onboarding answers. The coach confirms the final program assignment.
   */
  recommendedProgramLevel?: ('foundations' | 'development' | 'competitive') | null;
  /**
   * Set when the student completes the self-onboarding form.
   */
  onboardingCompletedAt?: string | null;
  trainingSessions?: {
    docs?: (string | TrainingSession)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  skillDevelopment?: {
    docs?: (string | SkillProgress)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  independentPracticeProgress?: {
    docs?: (string | IndependentPractice)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions".
 */
export interface TrainingSession {
  id: string;
  sessionKey?: string | null;
  source: 'manual' | 'program';
  title: string;
  student: string | StudentProfile;
  coach?: (string | null) | User;
  program?: (string | null) | Program;
  phase?: string | null;
  lessonWeek?: number | null;
  objective?: string | null;
  successCriteria?: string | null;
  /**
   * Choose 60, 90, or 120 minutes. The coaching plan redistributes time across all session blocks.
   */
  durationMinutes: number;
  /**
   * True when this session intentionally differs from the player’s program duration.
   */
  durationIsOverride?: boolean | null;
  /**
   * The session plan and coach scorecards share this list. Program sessions copy it from the program lesson.
   */
  skills?: (string | Skill)[] | null;
  /**
   * The student books the court and confirms the reserved date and time from their dashboard.
   */
  scheduledAt?: string | null;
  /**
   * Court name, branch and address supplied by the student after booking the venue.
   */
  location?: string | null;
  /**
   * Confirms that the student supplied this court booking.
   */
  courtBookedByStudent?: boolean | null;
  /**
   * Most recent time the student confirmed or changed the court booking.
   */
  courtBookingUpdatedAt?: string | null;
  /**
   * The student asked the coach for help finding a suitable venue.
   */
  courtHelpRequested?: boolean | null;
  courtHelpRequestedAt?: string | null;
  /**
   * Preferred city or area supplied by the student.
   */
  courtHelpArea?: string | null;
  courtHelpPreferredAt?: string | null;
  status: 'planned' | 'scheduled' | 'completed' | 'cancelled' | 'missed';
  completedAt?: string | null;
  attendance?: ('pending' | 'present' | 'late' | 'absent' | 'excused') | null;
  plan?: {
    warmUp?: string | null;
    movementPreparation?: string | null;
    technicalDrill?: (string | null) | Drill;
    progressiveDrill?: (string | null) | Drill;
    /**
     * Any third or later drill from a program lesson, including assessment benchmarks.
     */
    additionalDrills?: (string | Drill)[] | null;
    conditionedGame?: string | null;
    matchPlay?: string | null;
    cooldownAndFeedback?: string | null;
  };
  coachNotes?: string | null;
  studentSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-progress".
 */
export interface SkillProgress {
  id: string;
  progressKey?: string | null;
  label: string;
  student: string | StudentProfile;
  skill: string | Skill;
  stage: 'not-introduced' | 'learning' | 'controlled' | 'game-ready' | 'pressure-ready';
  progress: number;
  previousProgress?: number | null;
  coachFeedback?: string | null;
  latestSession?: (string | null) | TrainingSession;
  latestScore?: number | null;
  updatedAtAssessment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-skill-scores".
 */
export interface SessionSkillScore {
  id: string;
  scoreKey: string;
  label: string;
  session: string | TrainingSession;
  student: string | StudentProfile;
  coach?: (string | null) | User;
  program?: (string | null) | Program;
  lessonWeek?: number | null;
  skill: string | Skill;
  status: 'pending' | 'scored' | 'not-assessed';
  score?: number | null;
  /**
   * What the player demonstrated in this session.
   */
  evidence?: string | null;
  /**
   * The next coaching priority for this skill.
   */
  nextFocus?: string | null;
  scoredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: string;
  title: string;
  student: string | StudentProfile;
  drill: string | Drill;
  status: 'assigned' | 'in-progress' | 'completed';
  dueAt?: string | null;
  coachFeedback?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-events".
 */
export interface CoachingEvent {
  id: string;
  title: string;
  student: string | StudentProfile;
  eventType: 'assessment' | 'tournament' | 'other';
  startsAt: string;
  location?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add the times that players can choose. The player coordinates and supplies the booked court.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-availability".
 */
export interface CoachAvailability {
  id: string;
  coach: string | User;
  startsAt: string;
  durationMinutes: number;
  status: 'open' | 'blocked';
  updatedAt: string;
  createdAt: string;
}
/**
 * Set a repeating weekly time window. Students choose one of these times and supply the court they booked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-availability-rules".
 */
export interface CoachAvailabilityRule {
  id: string;
  /**
   * For example: Monday evenings
   */
  label: string;
  coach: string | User;
  weekday: '1' | '2' | '3' | '4' | '5' | '6' | '0';
  /**
   * 24-hour Manila time, for example 08:00 or 19:00.
   */
  startTime: string;
  /**
   * 24-hour Manila time. Must be later than the start time.
   */
  endTime: string;
  slotDurationMinutes: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-bookings".
 */
export interface AssessmentBooking {
  id: string;
  bookingKey: string;
  source?: ('scheduled' | 'direct') | null;
  student?: (string | null) | StudentProfile;
  slot?: (string | null) | CoachAvailability;
  availabilityRule?: (string | null) | CoachAvailabilityRule;
  coach: string | User;
  startsAt: string;
  durationMinutes: number;
  location: string;
  /**
   * The player needs help coordinating a court before the assessment.
   */
  courtHelpRequested?: boolean | null;
  /**
   * Preferred city or area for court coordination.
   */
  courtHelpArea?: string | null;
  playerName: string;
  email: string;
  phone?: string | null;
  playingExperience?: ('new' | 'under-1-year' | '1-3-years' | 'over-3-years') | null;
  preferredEvent?: ('singles' | 'doubles' | 'both' | 'not-sure') | null;
  goals?: string | null;
  trainingAvailability?: string | null;
  injuryConsiderations?: string | null;
  healthDataConsentAt?: string | null;
  privacyPolicyVersion?: string | null;
  /**
   * Additional information supplied by the player.
   */
  notes?: string | null;
  /**
   * The coach completes this structured 60-minute assessment in the coach dashboard.
   */
  assessmentResults?: {
    averageScore?: number | null;
    developmentStage?: ('not-introduced' | 'learning' | 'controlled' | 'game-ready' | 'pressure-ready') | null;
    recommendedPackage?: ('foundations' | 'development' | 'competitive') | null;
    movement?: {
      readyPosition?: number | null;
      fourCornerMovement?: number | null;
      frontCourtRecovery?: number | null;
      rearCourtRecovery?: number | null;
      balanceCoordination?: number | null;
    };
    technical?: {
      gripChanges?: number | null;
      lowServe?: number | null;
      overheadClear?: number | null;
      dropShot?: number | null;
      netShot?: number | null;
      lift?: number | null;
      drive?: number | null;
    };
    tactical?: {
      shotConsistency?: number | null;
      courtPositioning?: number | null;
      shotSelection?: number | null;
      recovery?: number | null;
      spaceAwareness?: number | null;
      performanceUnderPressure?: number | null;
    };
    strengths?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    trainingPriorities?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    firstSessionFocus?: string | null;
    independentPractice?: string | null;
    coachSummary?: string | null;
    completedAt?: string | null;
  };
  status: 'confirmed' | 'completed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendAssessmentReminder' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendAssessmentReminder' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'programs';
        value: string | Program;
      } | null)
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'drills';
        value: string | Drill;
      } | null)
    | ({
        relationTo: 'practice-library';
        value: string | PracticeLibrary;
      } | null)
    | ({
        relationTo: 'student-profiles';
        value: string | StudentProfile;
      } | null)
    | ({
        relationTo: 'training-sessions';
        value: string | TrainingSession;
      } | null)
    | ({
        relationTo: 'skill-progress';
        value: string | SkillProgress;
      } | null)
    | ({
        relationTo: 'session-skill-scores';
        value: string | SessionSkillScore;
      } | null)
    | ({
        relationTo: 'assignments';
        value: string | Assignment;
      } | null)
    | ({
        relationTo: 'independent-practices';
        value: string | IndependentPractice;
      } | null)
    | ({
        relationTo: 'coaching-events';
        value: string | CoachingEvent;
      } | null)
    | ({
        relationTo: 'coach-availability';
        value: string | CoachAvailability;
      } | null)
    | ({
        relationTo: 'coach-availability-rules';
        value: string | CoachAvailabilityRule;
      } | null)
    | ({
        relationTo: 'assessment-bookings';
        value: string | AssessmentBooking;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        coachHero?: T | CoachHeroBlockSelect<T>;
        developmentLoop?: T | DevelopmentLoopBlockSelect<T>;
        programsGrid?: T | ProgramsGridBlockSelect<T>;
        assessmentSteps?: T | AssessmentStepsBlockSelect<T>;
        trainingCycle?: T | TrainingCycleBlockSelect<T>;
        progressProfile?: T | ProgressProfileBlockSelect<T>;
        coachingQuote?: T | CoachingQuoteBlockSelect<T>;
        coachingCTA?: T | CoachingCTABlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachHeroBlock_select".
 */
export interface CoachHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  highlight?: T;
  description?: T;
  primaryButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  dashboard?:
    | T
    | {
        label?: T;
        title?: T;
        status?: T;
        stage?: T;
        skill?: T;
        feedback?: T;
        progress?: T;
        drillLabel?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DevelopmentLoopBlock_select".
 */
export interface DevelopmentLoopBlockSelect<T extends boolean = true> {
  label?: T;
  steps?:
    | T
    | {
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock_select".
 */
export interface ProgramsGridBlockSelect<T extends boolean = true> {
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  description?: T;
  programs?:
    | T
    | {
        number?: T;
        audience?: T;
        name?: T;
        description?: T;
        skills?:
          | T
          | {
              skill?: T;
              id?: T;
            };
        linkLabel?: T;
        linkURL?: T;
        accent?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssessmentStepsBlock_select".
 */
export interface AssessmentStepsBlockSelect<T extends boolean = true> {
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  description?: T;
  stepLabel?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrainingCycleBlock_select".
 */
export interface TrainingCycleBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  note?: T;
  sessions?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgressProfileBlock_select".
 */
export interface ProgressProfileBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  stages?:
    | T
    | {
        label?: T;
        id?: T;
      };
  profileTitle?: T;
  profileLabel?: T;
  skills?:
    | T
    | {
        name?: T;
        stage?: T;
        progress?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachingQuoteBlock_select".
 */
export interface CoachingQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoachingCTABlock_select".
 */
export interface CoachingCTABlockSelect<T extends boolean = true> {
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  googleSubject?: T;
  roles?: T;
  accountStatus?: T;
  invitationAcceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  level?: T;
  description?: T;
  durationWeeks?: T;
  phases?:
    | T
    | {
        name?: T;
        description?: T;
        order?: T;
        startWeek?: T;
        endWeek?: T;
        lessons?:
          | T
          | {
              week?: T;
              title?: T;
              lessonType?: T;
              objective?: T;
              durationMinutes?: T;
              skills?: T;
              drills?: T;
              eventVariants?:
                | T
                | {
                    singlesDrills?: T;
                    doublesDrills?: T;
                    singlesHomeDrills?: T;
                    doublesHomeDrills?: T;
                  };
              homePracticeInstructions?: T;
              homeDrills?: T;
              independentPractice?: T;
              successCriteria?: T;
              sessionPlan?:
                | T
                | {
                    warmUp?: T;
                    movementPreparation?: T;
                    conditionedGame?: T;
                    matchPlay?: T;
                    cooldownAndFeedback?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  independentPractices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drills_select".
 */
export interface DrillsSelect<T extends boolean = true> {
  name?: T;
  skill?: T;
  level?: T;
  eventType?: T;
  practiceSetting?: T;
  equipment?: T;
  numberOfPlayers?: T;
  durationMinutes?: T;
  instructions?: T;
  coachingPoints?: T;
  commonMistakes?: T;
  difficulty?: T;
  videoURL?: T;
  illustrationURL?: T;
  stepIllustrationURL?: T;
  stepIllustrationColumns?: T;
  stepIllustrationRows?: T;
  practiceSteps?:
    | T
    | {
        title?: T;
        instruction?: T;
        amount?: T;
        durationSeconds?: T;
        id?: T;
      };
  successTarget?: T;
  easierVariation?: T;
  harderProgression?: T;
  completionRequirement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-library_select".
 */
export interface PracticeLibrarySelect<T extends boolean = true> {
  name?: T;
  level?: T;
  instructions?: T;
  drills?: T;
  durationMinutes?: T;
  successCriteria?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-profiles_select".
 */
export interface StudentProfilesSelect<T extends boolean = true> {
  displayName?: T;
  user?: T;
  coach?: T;
  program?: T;
  currentProgramWeek?: T;
  currentPhase?: T;
  weeklyFocus?: T;
  focusExplanation?: T;
  packageName?: T;
  packageSessions?: T;
  sessionsRemaining?: T;
  attendanceRate?: T;
  assessmentStatus?: T;
  lastTrainingAt?: T;
  playingExperience?: T;
  preferredEvent?: T;
  trainingDurationMinutes?: T;
  goals?: T;
  trainingAvailability?: T;
  injuryConsiderations?: T;
  healthDataConsentAt?: T;
  privacyPolicyVersion?: T;
  skillSelfRating?: T;
  trainingFrequencyPerWeek?: T;
  competitionGoal?: T;
  recommendedProgramLevel?: T;
  onboardingCompletedAt?: T;
  trainingSessions?: T;
  skillDevelopment?: T;
  independentPracticeProgress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions_select".
 */
export interface TrainingSessionsSelect<T extends boolean = true> {
  sessionKey?: T;
  source?: T;
  title?: T;
  student?: T;
  coach?: T;
  program?: T;
  phase?: T;
  lessonWeek?: T;
  objective?: T;
  successCriteria?: T;
  durationMinutes?: T;
  durationIsOverride?: T;
  skills?: T;
  scheduledAt?: T;
  location?: T;
  courtBookedByStudent?: T;
  courtBookingUpdatedAt?: T;
  courtHelpRequested?: T;
  courtHelpRequestedAt?: T;
  courtHelpArea?: T;
  courtHelpPreferredAt?: T;
  status?: T;
  completedAt?: T;
  attendance?: T;
  plan?:
    | T
    | {
        warmUp?: T;
        movementPreparation?: T;
        technicalDrill?: T;
        progressiveDrill?: T;
        additionalDrills?: T;
        conditionedGame?: T;
        matchPlay?: T;
        cooldownAndFeedback?: T;
      };
  coachNotes?: T;
  studentSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-progress_select".
 */
export interface SkillProgressSelect<T extends boolean = true> {
  progressKey?: T;
  label?: T;
  student?: T;
  skill?: T;
  stage?: T;
  progress?: T;
  previousProgress?: T;
  coachFeedback?: T;
  latestSession?: T;
  latestScore?: T;
  updatedAtAssessment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-skill-scores_select".
 */
export interface SessionSkillScoresSelect<T extends boolean = true> {
  scoreKey?: T;
  label?: T;
  session?: T;
  student?: T;
  coach?: T;
  program?: T;
  lessonWeek?: T;
  skill?: T;
  status?: T;
  score?: T;
  evidence?: T;
  nextFocus?: T;
  scoredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  drill?: T;
  status?: T;
  dueAt?: T;
  coachFeedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "independent-practices_select".
 */
export interface IndependentPracticesSelect<T extends boolean = true> {
  practiceKey?: T;
  title?: T;
  practice?: T;
  student?: T;
  program?: T;
  phase?: T;
  lessonWeek?: T;
  instructions?: T;
  drills?: T;
  successCriteria?: T;
  status?: T;
  timerStatus?: T;
  timerStartedAt?: T;
  elapsedSeconds?: T;
  currentDrillIndex?: T;
  currentDrillElapsedSeconds?: T;
  currentStepIndex?: T;
  currentRound?: T;
  currentStepElapsedSeconds?: T;
  exerciseLogs?:
    | T
    | {
        drillIndex?: T;
        round?: T;
        stepIndex?: T;
        elapsedSeconds?: T;
        completedAt?: T;
        id?: T;
      };
  completedAt?: T;
  coachFeedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-events_select".
 */
export interface CoachingEventsSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  eventType?: T;
  startsAt?: T;
  location?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-availability_select".
 */
export interface CoachAvailabilitySelect<T extends boolean = true> {
  coach?: T;
  startsAt?: T;
  durationMinutes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-availability-rules_select".
 */
export interface CoachAvailabilityRulesSelect<T extends boolean = true> {
  label?: T;
  coach?: T;
  weekday?: T;
  startTime?: T;
  endTime?: T;
  slotDurationMinutes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-bookings_select".
 */
export interface AssessmentBookingsSelect<T extends boolean = true> {
  bookingKey?: T;
  source?: T;
  student?: T;
  slot?: T;
  availabilityRule?: T;
  coach?: T;
  startsAt?: T;
  durationMinutes?: T;
  location?: T;
  courtHelpRequested?: T;
  courtHelpArea?: T;
  playerName?: T;
  email?: T;
  phone?: T;
  playingExperience?: T;
  preferredEvent?: T;
  goals?: T;
  trainingAvailability?: T;
  injuryConsiderations?: T;
  healthDataConsentAt?: T;
  privacyPolicyVersion?: T;
  notes?: T;
  assessmentResults?:
    | T
    | {
        averageScore?: T;
        developmentStage?: T;
        recommendedPackage?: T;
        movement?:
          | T
          | {
              readyPosition?: T;
              fourCornerMovement?: T;
              frontCourtRecovery?: T;
              rearCourtRecovery?: T;
              balanceCoordination?: T;
            };
        technical?:
          | T
          | {
              gripChanges?: T;
              lowServe?: T;
              overheadClear?: T;
              dropShot?: T;
              netShot?: T;
              lift?: T;
              drive?: T;
            };
        tactical?:
          | T
          | {
              shotConsistency?: T;
              courtPositioning?: T;
              shotSelection?: T;
              recovery?: T;
              spaceAwareness?: T;
              performanceUnderPressure?: T;
            };
        strengths?:
          | T
          | {
              item?: T;
              id?: T;
            };
        trainingPriorities?:
          | T
          | {
              item?: T;
              id?: T;
            };
        firstSessionFocus?: T;
        independentPractice?: T;
        coachSummary?: T;
        completedAt?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Links displayed between the logo and the action buttons.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * These buttons are shown to signed-out visitors. Signed-in users see My dashboard instead.
   */
  actions: {
    secondaryAction: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
      label: string;
    };
    primaryAction: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Public pricing, service area, policies, coach profile, verified player proof, and health-data notice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-settings".
 */
export interface CoachingSetting {
  id: string;
  pricing: {
    label: string;
    assessmentFeePHP: number;
    session60PHP: number;
    session90PHP: number;
    session120PHP: number;
    billingNote: string;
    courtFeeMinPerHourPHP: number;
    courtFeeMaxPerHourPHP: number;
    courtFeeNote: string;
  };
  service: {
    area: string;
    details: string;
    venueOptions?:
      | {
          option: string;
          id?: string | null;
        }[]
      | null;
    travelPolicy: string;
  };
  cancellation: {
    noticeHours: number;
    reschedulePolicy: string;
    latePolicy: string;
    coachCancellationPolicy: string;
    venuePolicy: string;
  };
  /**
   * This section stays hidden publicly until a name and biography are supplied. Only publish credentials you can verify.
   */
  coachProfile?: {
    publicName?: string | null;
    title?: string | null;
    biography?: string | null;
    credentials?:
      | {
          credential: string;
          issuer?: string | null;
          year?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Only entries with publication permission enabled appear publicly. Use the player’s exact approved wording.
   */
  testimonials?:
    | {
        quote: string;
        displayName: string;
        playerContext?: string | null;
        outcome?: string | null;
        publicationPermission: boolean;
        id?: string | null;
      }[]
    | null;
  contact: {
    label: string;
    url: string;
  };
  privacy: {
    policyVersion: string;
    healthDataNotice: string;
    privacyURL: string;
    termsURL: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  actions?:
    | T
    | {
        secondaryAction?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        primaryAction?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-settings_select".
 */
export interface CoachingSettingsSelect<T extends boolean = true> {
  pricing?:
    | T
    | {
        label?: T;
        assessmentFeePHP?: T;
        session60PHP?: T;
        session90PHP?: T;
        session120PHP?: T;
        billingNote?: T;
        courtFeeMinPerHourPHP?: T;
        courtFeeMaxPerHourPHP?: T;
        courtFeeNote?: T;
      };
  service?:
    | T
    | {
        area?: T;
        details?: T;
        venueOptions?:
          | T
          | {
              option?: T;
              id?: T;
            };
        travelPolicy?: T;
      };
  cancellation?:
    | T
    | {
        noticeHours?: T;
        reschedulePolicy?: T;
        latePolicy?: T;
        coachCancellationPolicy?: T;
        venuePolicy?: T;
      };
  coachProfile?:
    | T
    | {
        publicName?: T;
        title?: T;
        biography?: T;
        credentials?:
          | T
          | {
              credential?: T;
              issuer?: T;
              year?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        quote?: T;
        displayName?: T;
        playerContext?: T;
        outcome?: T;
        publicationPermission?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        url?: T;
      };
  privacy?:
    | T
    | {
        policyVersion?: T;
        healthDataNotice?: T;
        privacyURL?: T;
        termsURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendAssessmentReminder".
 */
export interface TaskSendAssessmentReminder {
  input: {
    bookingID: string;
    reminder: 'one-day' | 'two-hours';
  };
  output: {
    sent: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}